config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  default_url_options host: Rails.application.credentials[Rails.env.to_sym][:host]

  scope constraints: Constraints::Html do
    get '/sign-out' => 'sessions#destroy', as: :sign_out
    scope '/auth' do
      get '/:provider/callback' => 'sessions#create'
      get '/failure' => 'sessions#failure'
    end
  end

  use_doorkeeper do
    controllers applications: 'oauth/applications', authorized_applications: 'oauth/authorized_applications'
  end

  scope constraints: Constraints::Application do
    resource :user, only: %i[edit update]

    resources :teams do
      scope module: :teams do
        resources :users
        resources :identities

        resources :checks do
          scope module: :checks do
            resources :charts, only: [] do
              collection do
                get 'history'
                get 'timeline'
              end
            end
          end
        end
        resources :check_configurations, only: [:create]
        resources :alerts
        resources :shifts
        resource :status_page, only: %i[edit update show] do
          scope module: :status_pages do
            resources :incidents
            resources :subscribers
          end
        end
      end
    end

    resources :browser_pushes, only: :create
  end

  scope constraints: Constraints::Html do
    resources :status_pages, only: :show do
      scope module: :status_pages do
        resources :subscribers, only: :create
      end
    end
  end

  namespace :team_identities do
    get '/slack/callback', to: 'callbacks#slack'

    get '/auth/:team_id/twitter', to: 'auths#twitter', as: 'auth_twitter'
    get '/twitter/callback', to: 'callbacks#twitter'
  end

  namespace :slacks do
    resource :event, only: [:create]
    resource :action, only: [:create]
  end

  namespace :confirmation do
    resource :alert_channels, only: :create
    resource :users, only: :create
  end

  mount Sidekiq::Web, at: '/worker'
end

app/models/status_page.rb
# frozen_string_literal: true

class StatusPage < ApplicationRecord
  include PublicActivity::Model
  include StatusPage::Initializable
  include StatusPage::WatchCheckPing
  include StatusPage::Subscribable
  include StatusPage::Checkable

  acts_as_paranoid

  tracked owner: proc { |_, _| Current.user }

  has_paper_trail only: %i[title]

  belongs_to :team
  has_many :status_page_incidents, dependent: :destroy

  validates :title, :team, presence: true

  include FriendlyId
  friendly_id :title, use: :slugged
end

app/models/status_page/checkable.rb
# frozen_string_literal: true

class StatusPage
  module Checkable
    extend ActiveSupport::Concern

    included do
      has_many :checks

      before_destroy :reset_checks
    end

    def success?
      checks.all? { |check| check.ping_state == 'success' }
    end

    private

    def reset_checks
      checks.update_all status_page_id: nil
    end
  end
end

app/models/status_page/initializable.rb
# frozen_string_literal: true

class StatusPage
  module Initializable
    extend ActiveSupport::Concern

    included do
      before_create :default_header
    end

    private

    def default_header
      return if header.present?

      self.header = <<~HEADER
        <h1>What is this site?</h1>
        <p>
          We continuously monitor the status of #{title}
          and all its related services. If there are any interruptions in service
          , a note will be posted here.
        </p>
      HEADER
    end
  end
end

app/models/status_page/notifier.rb
# frozen_string_literal: true

class StatusPage
  class Notifier
    def initialize(status_page, check)
      @status_page = status_page
      @check = check
    end

    def call
      return unless @check.on?(count: 10, state: 'error')

      @status_page.subscribers.find_each do |subscriber|
        SubscriberMailer.push(subscriber, @check).deliver_later
      end
    end
  end
end

app/models/status_page/subscribable.rb
# frozen_string_literal: true

class StatusPage
  module Subscribable
    extend ActiveSupport::Concern

    included do
      has_many :status_page_subscribers, dependent: :destroy
    end

    def notify_subscribers_about(check)
      Notifier.new(self, check).call
    end
  end
end

app/models/status_page/watch_check_ping.rb
# frozen_string_literal: true

class StatusPage
  module WatchCheckPing
    extend ActiveSupport::Concern

    class_methods do
      def check_ping_created(check_ping)
        check_ping.check.team.status_page.notify_subscribers_about(check_ping.check)
      end
    end
  end
end

app/controllers/status_pages/application_controller.rb
# frozen_string_literal: true

module StatusPages
  class ApplicationController < ::ApplicationController
    layout 'status_page'

    before_action :find_status_page

    private

    def find_status_page
      @status_page = StatusPage.friendly.find(params[:status_page_id])
    end
  end
end

app/controllers/status_pages/subscribers_controller.rb
# frozen_string_literal: true

module StatusPages
  class SubscribersController < StatusPages::ApplicationController
    def create
      @subscriber = @status_page.status_page_subscribers.build(status_page_subscriber_params)
      if @subscriber.valid?
        @subscriber.save
        redirect_to @status_page, notice: 'You have been added to the mailing list!'
      else
        flash.alert = 'There is a problem with your email address!'
        render 'status_pages/show'
      end
    end

    private

    def status_page_subscriber_params
      params.require(:status_page_subscriber).permit(:email)
    end
  end
end

app/controllers/status_pages_controller.rb
# frozen_string_literal: true

class StatusPagesController < ApplicationController
  layout 'status_page'

  before_action :find_status_page

  def show
    @subscriber = @status_page.status_page_subscribers.build
  end

  def find_status_page
    @status_page = StatusPage.friendly.find(params[:id])
  end
end

app/controllers/teams/status_pages/application_controller.rb
# frozen_string_literal: true

module Teams
  module StatusPages
    class ApplicationController < ::Teams::ApplicationController
      before_action :find_status_page

      private

      def find_status_page
        @status_page = policy_scope(StatusPage).first
      end
    end
  end
end

app/controllers/teams/status_pages/incidents_controller.rb
# frozen_string_literal: true

module Teams
  module StatusPages
    class IncidentsController < Teams::StatusPages::ApplicationController
      def index
        @incidents = policy_scope(StatusPageIncident)
        respond_to do |format|
          format.html { render :index }
          format.json { render json: @incidents }
        end
      end
    end
  end
end

app/controllers/teams/status_pages/subscribers_controller.rb
# frozen_string_literal: true

module Teams
  module StatusPages
    class SubscribersController < Teams::StatusPages::ApplicationController
      def index
        @subscribers = policy_scope(StatusPageSubscriber)
        respond_to do |format|
          format.html { render :index }
          format.json { render json: @subscribers }
        end
      end
    end
  end
end

app/controllers/teams/status_pages_controller.rb
# frozen_string_literal: true

module Teams
  class StatusPagesController < Teams::ApplicationController
    before_action :find_status_page, only: %i[edit show update]

    def show
      respond_to do |format|
        format.html { render :show }
        format.json { render json: @status_page }
      end
    end

    def edit
      authorize @status_page
      respond_to :html
    end

    def update
      authorize @status_page
      respond_to do |format|
        if @status_page.update_attributes(status_page_params)
          format.any(:js, :html) do
            redirect_to team_status_page_path(Current.team),
                        notice: 'Status Page was successfully updated.'
          end
          format.json { head :no_content }
        else
          format.html { render :edit }
          format.json { render json: @status_page.errors, status: :unprocessable_entity }
          format.js { render :update }
        end
      end
    end

    private

    def find_status_page
      @status_page = policy_scope(StatusPage).first
    end

    def status_page_params
      params.require(:status_page).permit(:title, :header, :footer, :domain_name, :subdomain, check_ids: [])
    end
  end
end

app/views/status_pages/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3 mt-5">
      <h3>
        <strong><%= @status_page.title %></strong>
        <span class="text-success">Status</span>
      </h3>
      <div class="hr-divider mb-5"></div>

      <% if @status_page.success? %>
        <div class="card card-outline-success text-center p-4 mb-4">
          <div class="card-block">
            <span class="text-success">All system operational!</span>
          </div>
        </div>
      <% end %>

      <%= raw @status_page.header %>


      <h4>Be Alerted</h4>
      <div class="hr-divider mb-4"></div>

      <fieldset class="mb-4">
        <%= simple_form_for @subscriber, url: status_page_subscribers_path(@status_page) do |f| %>
          <%= f.input :email, placeholder: 'e.g. john.doe@gmail.com' %>
          <div class="form-group">
            <%= f.submit 'Subscribe', class: 'btn btn-primary float-left' %>
          </div>
        <% end %>
      </fieldset>


      <h4>Availability</h4>
      <div class="hr-divider mb-4"></div>

      <div class="row">
        <% @status_page.checks.each do |check| %>
          <div class="col-6">
            <div class="p-3 statcard statcard-<%= check.ping_state %> mb-4">
              <h3 class="statcard-title"><%= check.name %></h3>
              <h3 class="statcard-number">
                <%= check.ping_total_time %>ms
              </h3>
            </div>
          </div>
        <% end %>
      </div>

      <h4>Incidents</h4>
      <div class="hr-divider"></div>
      <ul class="list-group mb-4">
        <% @status_page.status_page_incidents.order(created_at: :desc).first(100).each do |incident| %>
          <li class="list-group-item mb-2">
            <h5 class="d-flex align-self-start mr-3 badge #{badge_outline_color(incident)}">
              <%= incident.severity.capitalize %>
            </h5>

            <div class="media-body">
              <div class="media-heading">
                <small class="float-right text-muted">
                  <%= time_ago_in_words(incident.created_at) %>
                </small>
                <h6><%= incident.user.name %></h6>
              </div>
              <p><%= incident.body %></p>
            </div>
          </li>
        <% end %>
      </ul>

      <%= raw @status_page.footer %>
    </div>
  </div>
</div>