config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  default_url_options host: Rails.application.credentials[Rails.env.to_sym][:host]

  scope constraints: Constraints::Html do
    get '/sign-out' => 'sessions#destroy', as: :sign_out
    scope '/auth' do
      get '/:provider/callback' => 'sessions#create'
      get '/failure' => 'sessions#failure'
    end
  end

  use_doorkeeper do
    controllers applications: 'oauth/applications', authorized_applications: 'oauth/authorized_applications'
  end

  scope constraints: Constraints::Application do
    resource :user, only: %i[edit update]

    resources :teams do
      scope module: :teams do
        resources :users
        resources :identities

        resources :checks do
          scope module: :checks do
            resources :charts, only: [] do
              collection do
                get 'history'
                get 'timeline'
              end
            end
          end
        end
        resources :check_configurations, only: [:create]
        resources :alerts
        resources :shifts
        resource :status_page, only: %i[edit update show] do
          scope module: :status_pages do
            resources :incidents
            resources :subscribers
          end
        end
      end
    end

    resources :browser_pushes, only: :create
  end

  scope constraints: Constraints::Html do
    resources :status_pages, only: :show do
      scope module: :status_pages do
        resources :subscribers, only: :create
      end
    end
  end

  namespace :team_identities do
    get '/slack/callback', to: 'callbacks#slack'

    get '/auth/:team_id/twitter', to: 'auths#twitter', as: 'auth_twitter'
    get '/twitter/callback', to: 'callbacks#twitter'
  end

  namespace :slacks do
    resource :event, only: [:create]
    resource :action, only: [:create]
  end

  namespace :confirmation do
    resource :alert_channels, only: :create
    resource :users, only: :create
  end

  mount Sidekiq::Web, at: '/worker'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Concerns::Authenticable
  include Concerns::Trackable
  include Concerns::Authorizable
  include Concerns::Deviceable
  include Concerns::SignIn
  include Concerns::GoToApp
  include Concerns::Resetable
end

app/controllers/oauth/applications_controller.rb
# frozen_string_literal: true

module Oauth
  class ApplicationsController < Doorkeeper::ApplicationsController
    include Concerns::Authenticable
    include Concerns::Authorizable
    include Concerns::Deviceable
    include Concerns::GoToApp

    before_action :authenticated!
    before_action :set_application, only: %i[show edit update destroy]

    layout 'application'

    def index
      @applications = policy_scope(Doorkeeper::Application).order(:created_at).page params[:page]
      respond_to :html, :json
    end

    def create
      @application = Doorkeeper::Application.new(application_params)
      @application.owner = Current.user

      respond_to do |format|
        if @application.save
          format.any(:js, :html) { redirect_to oauth_applications_url, notice: 'Application was successfully created.' }
          format.json { render :show, status: :created, location: @alert }
        else
          format.html { render :new }
          format.json { render json: @application.errors, status: :unprocessable_entity }
          format.js { render :create }
        end
      end
    end

    def update
      respond_to do |format|
        if @application.update_attributes(application_params)
          format.any(:js, :html) { redirect_to oauth_applications_url, notice: 'Application was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :edit }
          format.json { render json: @application.errors, status: :unprocessable_entity }
          format.js { render :update }
        end
      end
    end

    private

    def set_application
      @application = policy_scope(Doorkeeper::Application).find(params[:id])
    end
  end
end

app/controllers/slacks/application_controller.rb
# frozen_string_literal: true

module Slacks
  class ApplicationController < ActionController::Base
    before_action :find_team_identities

    private

    def find_team_identities
      @team_identities = TeamIdentity.where(uid: team_id, provider: 'slack')
    end

    def team_id
      params[:team_id] || payload.dig('team', 'id')
    end

    def payload
      @payload ||= begin
                     JSON.parse(params[:payload])
                   rescue StandardError
                     {}
                   end
    end
  end
end

app/controllers/status_pages/application_controller.rb
# frozen_string_literal: true

module StatusPages
  class ApplicationController < ::ApplicationController
    layout 'status_page'

    before_action :find_status_page

    private

    def find_status_page
      @status_page = StatusPage.friendly.find(params[:status_page_id])
    end
  end
end

app/controllers/teams/application_controller.rb
# frozen_string_literal: true

module Teams
  class ApplicationController < ::ApplicationController
    before_action :authenticated!
    before_action :find_team

    private

    def find_team
      Current.team = policy_scope(Team).friendly.find(params[:team_id])
    end
  end
end

app/controllers/teams/checks/application_controller.rb
# frozen_string_literal: true

module Teams
  module Checks
    class ApplicationController < ::Teams::ApplicationController
      before_action :find_check

      private

      def find_check
        @check = policy_scope(Check).friendly.find(params[:check_id])
      end
    end
  end
end

app/controllers/teams/status_pages/application_controller.rb
# frozen_string_literal: true

module Teams
  module StatusPages
    class ApplicationController < ::Teams::ApplicationController
      before_action :find_status_page

      private

      def find_status_page
        @status_page = policy_scope(StatusPage).first
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :alert
      'alert-danger'
    when :notice
      'alert-success'
    else
      flash_type.to_s
    end
  end

  def avatar_url(source, default:)
    avatar = source.send(:avatar)
    avatar.attached? ? url_for(avatar) : default
  end
end

app/views/layouts/application/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="row">
    <div class="offset-lg-3 col-lg-6 offset-xl-4 col-xl-4">
      <div class="alert alert-dismissable <%= bootstrap_class_for(type) %>">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <%= message %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application/_header.html.erb
<div class="dashhead">
  <div class="dashhead-select dropdown">
    <a class="h4 nounderline text-dark dropdown-toggle"
       href="#"
       id="dropdownTeam"
       role="button"
       data-toggle="dropdown"
       aria-haspopup="true"
       aria-expanded="false">
      <% if Current.team.present? %>
        <% cache Current.team do %>
          <%= image_tag avatar_url(Current.team, default: 'users.svg'), height: 25 %>
          <%= Current.team.name %>
        <% end %>
      <% else %>
        Stack Alert
      <% end %>
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdownTeam">
      <p class="h4 ml-4">Switch Team</p>
      <div class="dropdown-divider"></div>
      <% cache ['header', Current.user.teams] do %>
        <% Current.user.teams.each do |team| %>
          <% cache ['header', team] do %>
            <%= link_to team_checks_path(team), class: "dropdown-item" do %>
              <%= image_tag avatar_url(team, default: 'users.svg'), height: 25 %>
              <%= team.name %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <div class="dropdown-divider"></div>
      <%= link_to new_team_path, class: "dropdown-item" do %>
        <%= fa_icon "plus", text: "Add a new Team" %>
      <% end %>
    </div>
  </div>

  <div class="dashhead-titles d-none d-md-inline-block">
    <h3 class="dashhead-title"><%= title(yield :title) %></h3>
    <h6 class="dashhead-subtitle"><%= description(yield :description) %></h6>
  </div>

  <div class="dashhead-toolbar">
    <span class="dashhead-toolbar-divider"></span>
    <div class="dashhead-toolbar-item dropdown">
      <% cache ['header', Current.user] do %>
        <a class="nounderline px-4" href="#" id="dropdownProfile" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag avatar_url(Current.user, default: 'user.svg'), class: "rounded-circle", height: 30 %>
        </a>
      <% end %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownProfile">
        <%= link_to edit_user_path, class: "dropdown-item" do %>
          <%= fa_icon "user", text: "User Settings" %>
        <% end %>
        <%#= link_to oauth_applications_path, class: "dropdown-item" do %>
          <%#= fa_icon "laptop", text: "Developer" %>
        <%# end %>
        <%= link_to sign_out_path, class: "dropdown-item" do %>
          <%= fa_icon "sign-out", text: "Log Out" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="hr-divider mb-3"></div>

app/views/layouts/application/_progress.html.erb
<div class="invisible loading-container">
  <div class="loading">
    <%= fa_icon "circle-o-notch", class: "fa-spin fa-4x" %>
  </div>
</div>

app/views/layouts/application/_sidebar.html.erb
<nav class="iconav">
  <%= link_to go_to_app_path, class: "iconav-brand" do %>
    <%= image_tag "brand-dark.svg", height: 40, class: "iconav-brand-icon" %>
  <% end %>
  <% if Current.team.present? %>
    <div class="iconav-slider">
      <ul class="nav iconav-nav flex-md-column">
        <li class="nav-item">
          <%= active_link_to team_checks_path(Current.team), class: "nav-link", title: "Checks" do %>
            <%= fa_icon "cogs", class: "fa-1-5x" %>
            <small class="iconav-nav-label d-md-none">Checks</small>
          <% end %>
        </li>
        <li class="nav-item">
          <%= active_link_to team_alerts_path(Current.team), class: "nav-link", title: "Alerts" do %>
            <%= fa_icon "bell", class: "fa-1-5x" %>
            <small class="iconav-nav-label d-md-none">Alerts</small>
          <% end %>
        </li>
        <li class="nav-item">
          <%= active_link_to team_status_page_path(Current.team), class: "nav-link", title: "Status Page" do %>
            <%= fa_icon "check", class: "fa-1-5x" %>
            <small class="iconav-nav-label d-md-none">Status Page</small>
          <% end %>
        </li>
        <li class="nav-item">
          <%= active_link_to team_shifts_path(Current.team), class: "nav-link", title: "Shifts" do %>
            <%= fa_icon "calendar", class: "fa-1-5x" %>
            <small class="iconav-nav-label d-md-none">Shifts</small>
          <% end %>
        </li>
        <li class="nav-item">
          <%= active_link_to Current.team, class: "nav-link", active: [["teams"], ["show", "edit"]], title: "Team" do %>
            <%= fa_icon "users", class: "fa-1-5x" %>
            <small class="iconav-nav-label d-md-none">Team</small>
          <% end %>
        </li>
      </ul>
    </div>
  <% end %>
</nav>